notifications:
  on_success: never
  on_failure: never

language: generic
os: linux
dist: xenial
env:
  - PY_VERSION='3.8'

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  - bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -q -n ammolite-dev python=$PY_VERSION
  - conda install -n ammolite-dev -c conda-forge pymol-open-source poetry
  - source activate ammolite-dev
  - poetry install

script:
  - pytest

before_deploy:
  - poetry build
  - sphinx-build ./doc ./build/doc
  - cd ./build
  - zip -r doc.zip doc
  - cd ..
  - mv ./build/doc.zip ./dist/doc.zip

deploy:
  provider: releases
  token:
    secure: taSv8rGvDPBT1hEfHFZWK6QbsTg2Nbnlu9WCaZ/JcZExvM2U5fQoBigxh7JKKQTl6kSQnPkaG23X1UqhAszIoEdyKrKWw4bDKU7imD68g01CEtLRheDK7gSdcQtoXgfOS7pm5O0eMjdFaBIQ6x0Euq5Al6dgPD3Z6/JSItgQe7ds6Cb2kLiBJL728U7aQY20lqrARDj0XACWlitdwJhFKL5eyfZfOwdb6LE4Sp84JUm2DVnQxgeg26YrdQBRG4SpUQwKuOy3EPqsrDUdGqz5sNF5HrhWJjQxrmHx8TF58Chp9u4vy0pBb3eoV72fGs1Dc9Ibj76NTW2sbyJ52Tf+Cd9aCTfx3u2/yRxzqLkcgrKOPmFKzcePq+YOqKX92myezdK1xg5GxzpwGeaMsFrL6Iy5OQeUv9xH0ByDSXGfwvaCh4RwHpZmdu7cokpAvNiSgSl9fXwfoIdz9xmiuhwtJ00n+UdjhWrhcBng3JKoFEfIaagU3K4LrC4Cc1BluLdRe7PmO6Qof4w2RE1JqeKvSJ5Ik0JJIAMAZDJzJOHn39VutfJ6FFIc8wwp+VjYpT5jHLxpLSxJAeZ4fshLO+uVpmRX7JoNDDDZjSs/2XSwfd7Fr+4lNfbb00cb1dJ2rkRBDGesYGNwzXKZJN5JgAwEjtnBHuD/XNFsudPlhcRkTag=
  file:
    - dist/*
    - doc/_build/doc.zip
  file_glob: true
  on:
    repo: biotite-dev/ammolite
    tags: true
  skip_cleanup: true
