# Conda environment, that includes all packages that are necessary for
# the complete Ammolite development process.

name: ammolite-dev

channels:
  - anaconda
  - conda-forge
  - tpeulen

dependencies:
  - python =3.8
  - poetry >=1.0
  - biotite >=0.21
  - matplotlib >=2.0
  - sphinx >=1.7
  - numpydoc >=0.8
  - pymol >=2.0
